document.addEventListener('DOMContentLoaded', (Event) => {
    //global variables that will be used by the entire program
    let hiddenWord = [];
    let maxTries = 10;
    let rightLetter = [];
    let wrongLetter = [];

    //manipulating the DOM
    let docUnderScore = document.getElementsByClassName("underscores");
    let rightGuess = document.getElementsByClassName('right_letter');
    let wrongGuess = document.getElementsByClassName('wrong_letter');
    let loser = document.getElementsByClassName('lose')
    let remaining = document.getElementsByClassName('remaining')
    let button = document.getElementById('button')
    let paragraph = document.getElementsByClassName('win_text')

    // this function generates a random word using words from a array of words
    const randomGen = (arr) => {
        let wordGenerator = arr[Math.floor(Math.random() * words.length)];
        let ranWordSplit = wordGenerator.split('');
        console.log(ranWordSplit, "the split word")
        return ranWordSplit

    }
    debugger
    //this function creates an array of underscores based on the length of the random word
    const underScore = (word) => {
        for (let i = 0; i < word.length; i++) {
            hiddenWord[i] = "_";
        }
        return hiddenWord
    }

    //ensure that the array doesn't contain any
    function checkRightLetter(userInput) {
        if (!rightLetter.includes(userInput)) {
            rightLetter.push(userInput)
        }
    }

    /* 
    assigning a variable with the random word generated by the function call
    the variable hideWord will equal the call of the underscore function
     */
    let randWord = randomGen(words);
    let hideWord = underScore(randWord);

    //checks to see if the character entered is inside of the randomly generated word
    function validity(arg1, arg2) {

        //pre-assigning element with value to be changed later
        docUnderScore[0].innerHTML = arg2.join(' ')
        remaining[0].innerHTML = `You have ${maxTries} lives remaining`
        //while (maxTries > 5) {
        console.log(arg2);
        console.log(`you have ${maxTries} left`);
        document.addEventListener('keypress', tester = (event) => {
            //this allows the user to press a key which gives a code for the key
            //the code is then converted back into a string and the 
            let keyCode = event.keyCode;
            let keyWord = String.fromCharCode(keyCode)
            for (let l = 0; l < arg1.length; l++) {
                //checking if the letter is inside of the array and the space contains an underscore
                //the array with the underscore arg2 will be updated with the letter at the same index as in the 
                //array with the random letter
                if (arg1[l].toLowerCase() === keyWord.toLowerCase() && arg2[l] === "_") {
                    arg2[l] = keyWord.toLowerCase();
                    console.log("keyWord", keyWord)
                    // this function ensures that the letter is not duplicated in the array
                    checkRightLetter(keyWord.toLowerCase())
                    console.log(rightLetter);

                    docUnderScore[0].innerHTML = arg2.join(' ');
                    rightGuess[0].innerHTML = rightLetter.join(' ');
                    console.log(hiddenWord, "the hiddenWord");
                    // creating a win condition  to informs the user that they have won
                    if (arg1.join('') === arg2.join('')) {
                        paragraph[0].innerHTML = `You won`
                        console.log(paragraph);
                        sound.src = "./2018-04-02_-_Beautiful_Village_-_David_Fesliyan.mp3"
                        sound.currentTime = 5;
                        button.style.visibility = "visible"
                        document.removeEventListener('keypress', tester)
                    }
                }
            }
            //decrementing the counter if player enters a letter not in the current word
            if (!arg1.includes(keyWord.toLowerCase())) {
                maxTries--;
                wrongLetter.push(keyWord.toLowerCase())
                wrongGuess[0].innerHTML = wrongLetter.join(' ')
                remaining[0].innerHTML = `You have ${maxTries} lives remaining`
                // calling the image function to run whenever the player makes a bad guess
                image();

                if (wrongLetter.includes(keyWord)) {
                    console.log('hello');

                }
            }
            if (maxTries === 0) {
                loser[0].innerHTML = `You lost. Press button to restart.`;
                docUnderScore[0].innerHTML = arg1.join(' ');
                document.removeEventListener('keypress', tester)
                button.style.visibility = "visible"
            }
            console.log(maxTries);
        })


    }

    // creating new sound and image elements
    let img = document.createElement('img')
    let sound = document.querySelector('audio')
    //this function uses a switch statement to replace the sources of the image tag with 
    //an updated image of the hang man picture
    //it also initiates a sound to start when the player uses first life
    function image() {
        switch (maxTries) {
            case 9:
                img.src = './Drawing.jpeg'
                sound.src = './2019-06-18_-_Creepy_Vibes_-_David_Fesliyan.mp3'
                sound.addEventListener('play', () => {})
                break;
            case 8:
                img.src = './Drawing (1).jpeg'
                break;
            case 7:
                img.src = './Drawing (2).jpeg'
                break;
            case 6:
                img.src = './Drawing (3).jpeg'
                break;
            case 5:
                img.src = './Drawing (4).jpeg'
                break;
            case 4:
                img.src = './Drawing (5).jpeg'
                break;
            case 3:
                img.src = './Drawing (6).jpeg'
                break;
            case 2:
                img.src = './Drawing (7).jpeg'
                break;
            case 1:
                img.src = './Drawing (8).jpeg'
                break;
            case 0:
                img.src = './Drawing (9).jpeg'

                break;
        }
        //document.body.appendChild(img)
        if (img !== null) {
            document.body.replaceChild(img, img)
        }
    }
    //appending the img element to the body 
    document.body.appendChild(img)


    //function that will start the game to run 
    const runGame = () => {
        validity(randWord, hideWord)
    }
    // when the document eventListener 'DOMContentLoaded' is triggered  
    //the runGame function will be triggered and perform all the function calls
    runGame();
    button.style.visibility = "hidden"
    button.addEventListener('click', () => {
        document.location.reload(true);
        // button.style.visibility = "hidden"
    })
})